openapi: 3.0.0
info:
  title: API Documentation
  description: This is the API documentation for the project.
  version: 0.0.1
servers:
  - url: http://localhost:3000
    description: Development server for testing

components:
  schemas:
    DatiBase:
      description: Oggetto contenente le informazioni di base di un quartiere.
      type: object
      properties:
        popolazione:
            type: integer
            description: Numero di abitanti del quartiere.
        superficie:
          type: number
          description: Superficie del quartiere in km^2.
          format: double
        etaMedia:
          type: number
          description: Età media degli abitanti del quartiere.
          format: double
        soddisfazioneMedia:
          type: number
          description: Soddisfazione media degli abitanti del quartiere.
          format: double
          minimum: 0
          maximum: 100
    ServiziGenerali:
      description: Oggetto contenente le informazioni sui servizi presenti in un quartiere.
      type: object
      properties:
        parchi:
          type: integer
          description: Numero di parchi presenti nel quartiere.
          minimum: 0
        scuole:
          type: integer
          description: Numero di scuole presenti nel quartiere.
          minimum: 0
        ristoranti:
          type: integer
          description: Numero di ristoranti presenti nel quartiere.
          minimum: 0
        luoghiDiSvago:
          type: integer
          description: Numero di luoghi di svago presenti nel quartiere.
          minimum: 0
        supermercati:
          type: integer
          description: Numero di supermercati presenti nel quartiere.
          minimum: 0
        farmacie:
          type: integer
          description: Numero di farmacie presenti nel quartiere.
          minimum: 0
    Coordinate:
      description: Array di coordinate che definiscono un quartiere e/o circoscrizione.
      type: array
      items: 
        description: Coordinate nel formato [latitude, longitude].
        type: array
        items:
          type: number
          format: double
        minItems: 2
        maxItems: 2
      minItems: 1
      uniqueItems: true
    Soddisfazione: 
        type: "number"
        description: "Soddisfazione media degli abitanti del quartiere."
        format: "double"
        minimum: 0
        maximum: 100
    CircoscrizioneBase: 
      description: Oggetto contenente le informazioni di Base di una circoscrizione.
      type: object
      properties:
        id:
          type: integer
          description: Identificatore univoco della circoscrizione.
        nome:
          type: string
          description: Nome della circoscrizione.
        coordinate:
          "$ref": "#/components/schemas/Coordinate"
        soddisfazione:
          "$ref": "#/components/schemas/Soddisfazione"
    Circoscrizione:
      description: Oggetto contenente le informazioni di una circoscrizione.
      allOf:
        - "$ref": "#/components/schemas/CircoscrizioneBase"
        - "$ref": "#/components/schemas/DatiBase"
      type: object
      properties:
        servizi:
          "$ref": "#/components/schemas/ServiziGenerali"
        storicoSoddisfazione:
          "$ref": "#/components/schemas/ArrayStoricoSoddisfazione"
    QuartiereBase: 
      description: Oggetto contenente le informazioni di base di un quartiere.
      type: object
      properties:
        id:
          type: "integer"
          description: "Identificatore univoco del quartiere."
        nome:
          type: "string"
          description: "Nome del quartiere."
        coordinate:
          "$ref": "#/components/schemas/Coordinate"
        circoscrizione:
          "$ref": "#/components/schemas/CircoscrizioneBase"
        soddisfazione:
          "$ref": "#/components/schemas/Soddisfazione"
    Quartiere: 
      description: Oggetto contenente le informazioni di un quartiere.
      allOf:
        - "$ref": "#/components/schemas/QuartiereBase"
        - "$ref": "#/components/schemas/DatiBase"
      type: object
      properties:
        servizi:
          "$ref": "#/components/schemas/ServiziGenerali"
        storicoSoddisfazione:
          "$ref": "#/components/schemas/ArrayStoricoSoddisfazione"
    StoricoSoddisfazione:
      description: Oggetto contenente le informazioni storiche sulla soddisfazione di un quartiere.
      type: object
      properties:
        data:
          type: string
          description: Data in cui è stata effettuata la misurazione.
          format: date
        soddisfazione:
          "$ref": "#/components/schemas/Soddisfazione"
    ArrayStoricoSoddisfazione:
      description: Array di oggetti contenenti le informazioni storiche sulla soddisfazione di un quartiere.
      type: array
      items:
        "$ref": "#/components/schemas/StoricoSoddisfazione"
    User:
      description: Oggetto contenente le informazioni di un utente.
      type: object
      properties:
        email:
          type: string
          description: Email dell'utente.
        nome:
          type: string
          description: Nome dell'utente.
        cognome:
          type: string
          description: Cognome dell'utente.
        ruolo:
          type: string
          enum:
            - "amministratore"
            - "analista"
            - "sondaggista"
            - "circoscrizione"
          description: Ruolo dell'utente.
    Session: 
      description: Oggetto contenente le informazioni di una sessione.
      type: object
      properties:
        token:
          type: string
          description: Token di autenticazione dell'utente.
        user:
          "$ref": "#/components/schemas/User"
    Error:
      description: Oggetto contenente le informazioni di un errore.
      type: object
      properties:
        code:
          type: integer
          description: Codice dell'errore.
        message:
          type: string
          description: Messaggio di errore.
        details:
          type: string
          description: Dettagli dell'errore.
          nullable: true

paths:
  '/api/quartieri' :
    description: "Risorsa che restituisce la lista dei quartieri di Trento."
    get: 
      description: "Ritorna una lista di tutti i quartieri della città di Trento."
      parameters:
        - name: deepData
          in: query
          description: "Se impostato a true, restituisce le informazioni complete di ogni quartiere."
          required: false
          schema:
            type: boolean
            default: false
          allowEmptyValue: true
      responses: 
        200: 
          description: "Successful response"
          content:
            application/json:
              schema: 
                oneOf:
                  - type: array
                    items: 
                      "$ref": "#/components/schemas/QuartiereBase"
                  - type: array
                    items: 
                      "$ref": "#/components/schemas/Quartiere"
  '/api/quartieri/{id}' :
    description: "Risorsa che restituisce le informazioni di un quartiere di Trento con le informazioni di base e i servizi presenti."
    get: 
      responses: 
        200:
          description: "Risposta con le informazioni del quartiere."
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Quartiere"
        404: 
          description: "Quartiere non trovato."
          content: 
            application/json: 
              schema: 
                "$ref": "#/components/schemas/Error"
  '/api/circoscrizioni' : 
    description: "Risorsa che restituisce la lista delle circoscrizioni di Trento."
    get: 
      description: "Returns a list of all the districts in the city of Trento."
      parameters:
        - name: deepData
          in: query
          description: "Se impostato a true, restituisce le informazioni complete di ogni circoscrizione."
          required: false
          schema:
            type: boolean
            default: false
          allowEmptyValue: true
      responses:
        200 :
          description: "Successful response"
          content:
            application/json:
              schema: 
                oneOf:
                  - type: "array"
                    items: 
                      "$ref": "#/components/schemas/CircoscrizioneBase"
                  - type: "array"
                    items: 
                      "$ref": "#/components/schemas/Circoscrizione"
  '/api/circoscrizioni/{id}' :
    description: "Risorsa che restituisce le informazioni di una circoscrizione di Trento con le informazioni di base e i servizi presenti."
    get: 
      responses: 
        200:
          description: "Risposta con le informazioni della circoscrizione."
          content:
            application/json: 
              schema: 
                $ref: "#/components/schemas/Circoscrizione"
        404: 
          description: "Circoscrizione non trovata."
          content: 
            application/json: 
              schema: 
                "$ref": "#/components/schemas/Error"
  '/api/generalInfo' :
    description: "Risorsa che restituisce le informazioni generali della città di Trento."
    get: 
      description: "Restituisce le informazioni generali della città di Trento."
      responses: 
        200 : 
          description: "Successful response"
          content: 
            application/json:
              schema: 
                type: "object"
                properties: 
                  popolazione :
                    type: integer
                    description: "Numero di abitanti della città di Trento."
                  superficie :
                    type: number
                    description: "Superficie della città di Trento in km^2."
                    format: double
                  etaMedia :
                    type: number
                    description: "Età media degli abitanti della città di Trento."
                    format: double
                  soddisfazioneMedia: 
                    type: number
                    description: "Soddisfazione media degli abitanti della città di Trento."
                    format: double
                    minimum: 0
                    maximum: 100
  '/api/session':
    description: "Risorsa che restituisce le informazioni della sessione dell'utente."
    get:
      description: "Restituisce le informazioni della sessione dell'utente, se presente."
      parameters:
        - name: token
          in: header
          description: "Token di autenticazione dell'utente."
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Successful response"
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        401:
          description: "Utente non autenticato."
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
        404:
          description: "Sessione non trovata."
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
    post: 
      description: "Crea una nuova sessione per l'utente."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: "Email dell'utente."
                password:
                  type: string
                  description: "Password (codificata) dell'utente."
      responses:
        200:
          description: "Sessione creata con successo."
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Session"
        401:
          description: "Credenziali non valide."
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"