name: LatexD1 CI
run-name: Building LaTeX Deliverable 1 file
on: [pull_request]
jobs:
  # Build usign Github Action for LaTeX
  build_latex:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Git
        uses: actions/checkout@v4
      - name: Build LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          working_directory: deliverable/D1
          root_file: main.tex
