name: LatexD1 CI
run-name: Building LaTeX Deliverable 1 file
on: 
  push:
      paths:
        - 'deliverable/D1/**'
        - 'deliverable/images/**'
jobs:
  # Build usign Github Action for LaTeX
  build_latex:
      runs-on: ubuntu-latest
      steps:
      - name: Set up Git
        uses: actions/checkout@v4
      - name: Build LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          working_directory: deliverable/D1
          root_file: main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Deliverable1
          path: deliverable/D1/main.pdf